services:
  nostrbook-relay:
    build:
      context: ./relay
    ports:
      - "7777:7777"
    environment:
      WS_PORT: "7777"
      STORAGE_PATH: "/app/data"
      SWARM_TOPIC: "nostrbook-dev"
      RELAY_NAME: "nostrbook-dev"
      WOT_DISCOVERY: "true"
    volumes:
      - relay-dev-data:/app/data
    deploy:
      resources:
        limits:
          memory: 512M

  nostrbook-translate:
    image: libretranslate/libretranslate:latest
    ports:
      - "5000:5000"
    environment:
      LT_LOAD_ONLY: "en,es"
    deploy:
      resources:
        limits:
          memory: 512M

volumes:
  relay-dev-data:
